name: 📦 Go Package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  index-package:
    runs-on: ubuntu-latest
    steps:
      - name: Index go.dev/packages
        run: |
          curl -sk https://sum.golang.org/lookup/github.com/maxwu/gotest-labels@${{ github.ref_name }}
